site_name: Network Echos
# site_url: https://mydomain.org/mysite
repo_url: https://github.com/garland-culbreth/network-echos
repo_name: garland-culbreth/network-echos

plugins:
  - search

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
      block_tag: 'pre'

extra_javascript:
  - ./javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
  - Concepts:
    - concepts/model.md
    - concepts/notation.md
  - API reference:
    - api-reference/core.md
    - api-reference/plot.md
  - User guide:
    - user-guide/getting-started.md
